import Database from "better-sqlite3";
import path from "path";

// BASE_DIR = os.path.join(os.environ["APPDATA"], "WorkSight")
// DB_PATH = os.path.join(BASE_DIR, "worksight.db")

const dbPath = path.join(process.env.APPDATA!, "WorkSight", "worksight.db");
export const db = new Database(dbPath);


export function getDayAppUsage(date: string) {
  return db.prepare(`
    SELECT app_name, SUM(duration_sec) AS total_sec
    FROM activity_log
    WHERE DATE(start_time) = ?
    GROUP BY app_name
    ORDER BY total_sec DESC
  `).all(date);
}

export function updateUserProfile(profileData: any) {
  ensureUserProfileTable();

  return db.prepare(`
    UPDATE user_profile
    SET
      username = ?,
      agent_nickname = ?,
      email = ?,
      system_prompt = ?,
      final_goal = ?,
      productive_apps = ?,
      distraction_apps = ?,
      neutral_apps = ?,
      api_key= ?
    WHERE id = 1
  `).run(
    profileData.username,
    profileData.agent_nickname,
    profileData.email,
    profileData.system_prompt,
    profileData.final_goal,
    JSON.stringify(profileData.productive_apps || []),
    JSON.stringify(profileData.distraction_apps || []),
    JSON.stringify(profileData.neutral_apps || []),
    profileData.api_key
  );
}

/* ---------- SAFE TABLE + COLUMN ENSURE ---------- */

function ensureUserProfileTable() {
  // create table safely
 
  db.prepare(`
    CREATE TABLE IF NOT EXISTS user_profile (
      id INTEGER PRIMARY KEY,
      username TEXT,
      agent_nickname TEXT,
      email TEXT,
      system_prompt TEXT,
      final_goal TEXT,
      productive_apps TEXT,
      distraction_apps TEXT,
      neutral_apps TEXT,
      api_key TEXT
    )
  `).run();


  // // ensure row
  // db.prepare(`
  //   INSERT OR IGNORE INTO user_profile (id)
  //   VALUES (1)
  // `).run();

  // ensure columns (OLD DB FIX)
  // const cols = db
  //   .prepare(`PRAGMA table_info(user_profile)`)
  //   .all()
  //   .map((c: any) => c.name);

  // if (!cols.includes("productive_apps"))
  //   db.prepare(
  //     `ALTER TABLE user_profile ADD COLUMN productive_apps TEXT DEFAULT '[]'`
  //   ).run();

  // if (!cols.includes("distraction_apps"))
  //   db.prepare(
  //     `ALTER TABLE user_profile ADD COLUMN distraction_apps TEXT DEFAULT '[]'`
  //   ).run();

  // if (!cols.includes("neutral_apps"))
  //   db.prepare(
  //     `ALTER TABLE user_profile ADD COLUMN neutral_apps TEXT DEFAULT '[]'`
  //   ).run();
  //   if (!cols.includes("api_key"))
  // db.prepare(
  //   `ALTER TABLE user_profile ADD COLUMN api_key TEXT`
  // ).run();
}


export function getUserProfile() {
  ensureUserProfileTable();

  const row = db.prepare(
    "SELECT * FROM user_profile WHERE id = 1"
  ).get();

  return {
    ...row,
    productive_apps: JSON.parse(row.productive_apps || "[]"),
    distraction_apps: JSON.parse(row.distraction_apps || "[]"),
    neutral_apps: JSON.parse(row.neutral_apps || "[]"),
  };
}


export function getDaySummary(date: string) {
  return db.prepare(`
    SELECT category, SUM(duration_sec) AS total_sec
    FROM activity_log
    WHERE DATE(start_time) = ?
    GROUP BY category
  `).all(date);
}

export function getWeekSummary(startDate: string, endDate: string) {
  return db.prepare(`
   WITH RECURSIVE days(day) AS (
  SELECT date(?)
  UNION ALL
  SELECT date(day, '+1 day')
  FROM days
  WHERE day < date(?)
)
SELECT
  days.day,
  IFNULL(SUM(activity_log.duration_sec), 0) AS total_sec
FROM days
LEFT JOIN activity_log
  ON date(activity_log.start_time) = days.day
GROUP BY days.day
ORDER BY days.day;

  `).all(startDate, endDate);

 
}

export function getMonthSummary(year: number, month: number) {
  return db.prepare(`
    SELECT DATE(start_time) AS day, SUM(duration_sec) AS total_sec
    FROM activity_log
    WHERE strftime('%Y', start_time) = ?
      AND strftime('%m', start_time) = ?
    GROUP BY day
    ORDER BY day
  `).all(String(year), String(month).padStart(2, "0"));
}


// TABLE USED (STRICTLY):
// activity_log(
//   id INTEGER,
//   app_name TEXT,
//   window_title TEXT,
//   domain TEXT,
//   start_time TEXT,
//   end_time TEXT,
//   duration_sec INTEGER,
//   category TEXT
// )



 





/**
 * Run a SAFE SELECT-only SQL query generated by the AI.
 * - Only allows single SELECT statements
 * - Must reference at least one allowed table
 */
export function runSafeSQL(sql: string) {
  console.log("Running safe SQL query:");
  
  const cleaned = (sql || "").trim();
  const lowered = cleaned.toLowerCase();

  if (!lowered.startsWith("select")) {
    throw new Error("Only SELECT queries are allowed for safety reasons.");
  }

  if (lowered.includes(";")) {
    throw new Error("Multiple statements are not allowed.");
  }

  // ensure it references an allowed table
  const allowedTables = ["activity_log", "user_profile"];
  const referencesTable = allowedTables.some((t) => lowered.includes(t));
  if (!referencesTable) {
    throw new Error(
      `Query must reference one of the allowed tables: ${allowedTables.join(", ")}`
    );
  }

  return db.prepare(cleaned).all();
}

export function getuserGoal(){
  ensureUserProfileTable();
  const row = db.prepare(
    "SELECT *  FROM user_profile WHERE id = 1"
  ).get();
  return { finalGoal: row.final_goal, apiKey: row.api_key };
}

export function ensureLLMKeys() {
  db.prepare(`
    CREATE TABLE IF NOT EXISTS llm_api_keys (
      provider TEXT,
      model TEXT PRIMARY KEY,
      api_key TEXT NOT NULL
    )
  `).run();

   const stmt = db.prepare(`
    INSERT OR IGNORE INTO llm_api_keys (provider, model, api_key)
    VALUES (?, ?, '')
  `);

  stmt.run("openai", "gpt-4.5-turbo");
  stmt.run("gemini", "gemini-2.5-flash");
}
export function saveApiKeyForModel(provider: string, model: string, apiKey: string) {
  ensureLLMKeys();

  db.prepare(`
    INSERT OR REPLACE INTO llm_api_keys (provider, model, api_key)
    VALUES (?, ?, ?)
  `).run(provider, model, apiKey);


}
export function getApiKeyForModel(provider: string) {
  ensureLLMKeys();

  const row = db.prepare(
    "SELECT api_key FROM llm_api_keys WHERE provider = ?"
  ).get(provider);
  return row?.api_key || null;
}
